### ISSUE TITLE
[2.6.6_dev] History browser Only Bg data are ok on previous days

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2651]
Data used for treatments in History Browser comes from TreatmentsPlugin so it contains only last 24Hours + DIA history of treatments

If you select an older day, only BG data are Ok, all other data are missing or are wrong... (Basal rate and deviations are wrong, IOB, COB are missing...)

![Screenshot_20200516-114039_AndroidAPS](https://user-images.githubusercontent.com/52934600/82116589-384bad80-976b-11ea-8c41-baecf974c6c6.jpg)

I think TreatmentPlugin cannot be injected in iobCobCalculatorPlugin because it's necessary to use a different instance for historyBrowser (instance missing today in historyBrowser activity...)

Unfortunately, my knowledge of the injection mechanisms and this part of the code is not enough today to propose a correction for this issue :-(

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/eeb4ce1686d2e5b2dd427dc276cf4aae8c0c121b

**Comment by guydavies** [comment]
Original issue and fix confirmed on my phone.

Rgds,

Guy

**Comment by Philoul** [comment]
Cool
Even if I could not have done it, it is close to what I imagined and I understood the modification ...
👍

**Comment by Philoul** [comment]
Unfortunatly there still remains several issues on history browser: it's better with last commit but Carbs data are still missing (see screenshot below)

Left: screenshot of 05/19 taken on 05/20 at 8:23 a.m.
middle: screenshot of 05/19 taken on 05/21 at 10:28 p.m. without carbs
on the right: screenshot of 20/05 taken on 05/21 at10:26 p.m. (we see the limit of carbs data in the history browser the day before)

![HistoryBrowserBug1](https://user-images.githubusercontent.com/52934600/82644523-bdbeda00-9c11-11ea-9c19-38c0a87eb22d.jpg)
