### ISSUE TITLE
2.6.6-dev - Alert settings are ignored

### ISSUE THREAD

**Issue by nshtg** [MilosKozak/AndroidAPS#2652]
AndroidAPS 2.6.6-dev
Build: e98e5ec9d-2020.05.15-22:01
Remote: https://github.com/MilosKozak/AndroidAPS
Flavor: fullrelease
Nightscout version: 13.0.1
Engineering mode enabled

See screenshots attached. I have alerts disabled but I still get those alerts (only in app, not as android notification). I can mail logs if you need them.

![Screenshot_20200516-130934](https://user-images.githubusercontent.com/5219415/82118382-5ddeb400-9777-11ea-90f6-bd79e311c388.jpg)
![Screenshot_20200516-130958](https://user-images.githubusercontent.com/5219415/82118383-5e774a80-9777-11ea-8d2a-fa1e9f22f622.jpg)

**Comment by swissalpine** [comment]
I see the same behaviour: Notifications I never seen before ...

**Comment by MilosKozak** [comment]
fixed in dev. retest pls

**Comment by swissalpine** [comment]
Thanks, I will merge it soon and wait what happens ...

**Comment by CaroGo** [comment]
Same for me, get low alert although no alarm is set. 2.6.6.build f7f01de98 on 15.5.

**Comment by guydavies** [comment]
The latest Dev does seem to fix this. I've not seen a high alert after
lunch and I did breach my upper target.

**Comment by nshtg** [comment]
@MilosKozak 
Urgent high is fixed, but now I get high alerts:

![Screenshot_20200517-192528](https://user-images.githubusercontent.com/5219415/82155315-58b35f00-9874-11ea-81de-230455d79589.jpg)

**Comment by nshtg** [comment]
Urgent high is not fixed either:

![Screenshot_20200517-201712](https://user-images.githubusercontent.com/5219415/82156489-84861300-987b-11ea-8f20-0a05e092d2a0.jpg)

**Comment by swissalpine** [comment]
Yes. Unfortunatly not fixed.

**Comment by guydavies** [comment]
I've not seen the issue since and I've definitely been into the high (but not urgent high) zones. I haven't been low since updating.

**Comment by swissalpine** [comment]
@guydavies Good for you - we continue to make different experiences: It's not fixed.

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/8ae817cdda99b6d8794314da41d05f042b5d5e3b
